### ISSUE TITLE
rank based on multiple criteria

### ISSUE THREAD

**Issue by nxs5899** [thelahunginjeet/pyrankagg#1]
Hi Kevin. thank you for making this useful package for rank aggregation. 
my question is that how to apply those different ranking methods in rankagg.py to a multiple criteria problem. for instance, I want to rank football teams based on several attributes related to a team and lets assume that those attributes can be continuous or discrete.
thank you

**Comment by thelahunginjeet** [comment]
Hi nxs; thanks for your interest in the package.  I haven't thought much about multi criteria ranking because it's not the kind of problem I was trying to solve when writing the package; I don't know much about how to do that, but I could look into it.  The only way you could use this package with your problem is to create a score function that collapses your criteria into a single scalar score.
